from __future__ import annotations

DOMAIN = "fonrich_dc_monitor"

DEFAULT_NAME = "Fonrich DC Monitor"
DEFAULT_HOST = "192.168.0.41"
DEFAULT_PORT = 4002
DEFAULT_TIMEOUT = 3
DEFAULT_RETRIES = 1
DEFAULT_BAUDRATE = 9600
BAUDRATE_OPTIONS = [2400, 4800, 9600, 19200, 38400, 57600, 115200]

DEFAULT_CONTROLLER_1 = 240
DEFAULT_CONTROLLER_2 = 241
DEFAULT_CONTROLLER_3 = 242

CONF_HOST = "host"
CONF_PORT = "port"
CONF_TIMEOUT = "timeout"
CONF_RETRIES = "retries"
CONF_BAUDRATE = "baudrate"
CONF_CONTROLLERS = "controllers"
CONF_ENABLE_ARC_INTENSITY = "enable_arc_intensity"
CONF_SCAN_ALARM = "scan_alarm"
CONF_SCAN_BASE = "scan_base"
CONF_SCAN_POWER = "scan_power"
CONF_SCAN_ENERGY = "scan_energy"
CONF_SCAN_ARC_INTENSITY = "scan_arc_intensity"

DEFAULT_SCAN_ALARM = 10
DEFAULT_SCAN_BASE = 30
DEFAULT_SCAN_POWER = 60
DEFAULT_SCAN_ENERGY = 300
DEFAULT_SCAN_ARC_INTENSITY = 120

CONF_SCAN_HISTORY = "scan_history"
CONF_INTER_REQUEST_DELAY_MS = "inter_request_delay_ms"
CONF_INTER_CONTROLLER_DELAY_MS = "inter_controller_delay_ms"
CONF_STARTUP_STAGGER_SECONDS = "startup_stagger_seconds"
CONF_MAX_REGISTERS_PER_REQUEST = "max_registers_per_request"
CONF_ENABLE_POWER = "enable_power"
CONF_ENABLE_ENERGY = "enable_energy"
CONF_ENABLE_HISTORY = "enable_history"
CONF_ENABLE_BUTTONS = "enable_buttons"
CONF_ENABLE_ALARM_MASKS = "enable_alarm_masks"

DEFAULT_SCAN_HISTORY = 300
DEFAULT_INTER_REQUEST_DELAY_MS = 80
DEFAULT_INTER_CONTROLLER_DELAY_MS = 150
DEFAULT_STARTUP_STAGGER_SECONDS = 5
DEFAULT_MAX_REGISTERS_PER_REQUEST = 20
DEFAULT_ENABLE_POWER = True
DEFAULT_ENABLE_ENERGY = True
DEFAULT_ENABLE_HISTORY = True
DEFAULT_ENABLE_BUTTONS = True
DEFAULT_ENABLE_ALARM_MASKS = True

REGISTER_CLEAR_ARC_HISTORY = 3073
REGISTER_CLEAR_ALARM_TRIP = 3074
REGISTER_ARC_SELFTEST = 3077


CONF_CONTROLLER_SLAVES = "controller_slaves"
CONF_CONTROLLER_NAMES = "controller_names"
CONF_REQUIRE_ONLINE = "require_online"

DEFAULT_CONTROLLER_SLAVES = "240,241,242"
DEFAULT_CONTROLLER_NAMES = "V1 / Kasten 1,V2 / Kasten 2,V3 / Kasten 3"
DEFAULT_REQUIRE_ONLINE = True
