from __future__ import annotations

DOMAIN = "fonrich_dc_monitor"

DEFAULT_NAME = "Fonrich DC Monitor"
DEFAULT_HOST = "192.168.0.41"
DEFAULT_PORT = 4002
DEFAULT_TIMEOUT = 3
DEFAULT_RETRIES = 1
DEFAULT_BAUDRATE = 9600
BAUDRATE_OPTIONS = [2400, 4800, 9600, 19200, 38400, 57600, 115200]

CONF_PROTOCOL = "protocol"
PROTOCOL_MODBUS_TCP = "modbus_tcp_gateway"
PROTOCOL_RTU_OVER_TCP = "rtu_over_tcp"
DEFAULT_PROTOCOL = PROTOCOL_MODBUS_TCP
PROTOCOL_OPTIONS = [PROTOCOL_MODBUS_TCP, PROTOCOL_RTU_OVER_TCP]

CONF_HOST = "host"
CONF_PORT = "port"
CONF_TIMEOUT = "timeout"
CONF_RETRIES = "retries"
CONF_BAUDRATE = "baudrate"
CONF_CONTROLLERS = "controllers"
CONF_ENABLE_ARC_INTENSITY = "enable_arc_intensity"
CONF_SCAN_ALARM = "scan_alarm"
CONF_SCAN_BASE = "scan_base"
CONF_SCAN_POWER = "scan_power"
CONF_SCAN_ENERGY = "scan_energy"
CONF_SCAN_ARC_INTENSITY = "scan_arc_intensity"
CONF_SCAN_HISTORY = "scan_history"
CONF_INTER_REQUEST_DELAY_MS = "inter_request_delay_ms"
CONF_INTER_CONTROLLER_DELAY_MS = "inter_controller_delay_ms"
CONF_STARTUP_STAGGER_SECONDS = "startup_stagger_seconds"
CONF_MAX_REGISTERS_PER_REQUEST = "max_registers_per_request"
CONF_OFFLINE_AFTER_FAILURES = "offline_after_failures"
CONF_ENABLE_POWER = "enable_power"
CONF_ENABLE_ENERGY = "enable_energy"
CONF_ENABLE_HISTORY = "enable_history"
CONF_ENABLE_BUTTONS = "enable_buttons"
CONF_ENABLE_SAFETY_TEST_BUTTONS = "enable_safety_test_buttons"
CONF_REMOTE_TRIP_ARM_SECONDS = "remote_trip_arm_seconds"
CONF_TEST_MESSAGE_SECONDS = "test_message_seconds"
CONF_ENABLE_ALARM_MASKS = "enable_alarm_masks"
CONF_ENABLE_ALARM_BINARY_SENSORS = "enable_alarm_binary_sensors"
CONF_ENABLE_ALARM_TEXT_SENSOR = "enable_alarm_text_sensor"
CONF_ENABLE_DAILY_MAX_CURRENT = "enable_daily_max_current"
CONF_ENABLE_CHANNEL_VOLTAGE = "enable_channel_voltage"
CONF_SENSOR_PROFILE = "sensor_profile"
CONF_DI_DESCRIPTIONS = "di_descriptions"

SENSOR_PROFILE_PRODUCTION = "production"
SENSOR_PROFILE_STANDARD = "standard"
SENSOR_PROFILE_DIAGNOSTIC = "diagnostic"
SENSOR_PROFILE_OPTIONS = [SENSOR_PROFILE_PRODUCTION, SENSOR_PROFILE_STANDARD, SENSOR_PROFILE_DIAGNOSTIC]
DEFAULT_SENSOR_PROFILE = SENSOR_PROFILE_PRODUCTION

DEFAULT_SCAN_ALARM = 15
DEFAULT_SCAN_BASE = 30
DEFAULT_SCAN_POWER = 60
DEFAULT_SCAN_ENERGY = 300
DEFAULT_SCAN_ARC_INTENSITY = 300
DEFAULT_SCAN_HISTORY = 300
DEFAULT_INTER_REQUEST_DELAY_MS = 120
DEFAULT_INTER_CONTROLLER_DELAY_MS = 250
DEFAULT_STARTUP_STAGGER_SECONDS = 5
DEFAULT_MAX_REGISTERS_PER_REQUEST = 20
DEFAULT_OFFLINE_AFTER_FAILURES = 2
DEFAULT_ENABLE_POWER = True
DEFAULT_ENABLE_ENERGY = False
DEFAULT_ENABLE_HISTORY = False
DEFAULT_ENABLE_BUTTONS = True
DEFAULT_ENABLE_SAFETY_TEST_BUTTONS = False
DEFAULT_REMOTE_TRIP_ARM_SECONDS = 20
DEFAULT_TEST_MESSAGE_SECONDS = 60
DEFAULT_ENABLE_ALARM_MASKS = False
DEFAULT_ENABLE_ALARM_BINARY_SENSORS = False
DEFAULT_ENABLE_ALARM_TEXT_SENSOR = True
DEFAULT_ENABLE_DAILY_MAX_CURRENT = True
DEFAULT_ENABLE_CHANNEL_VOLTAGE = True

# Documented FR-DCMG-MMPS command and configuration registers.
REGISTER_CLEAR_ARC_HISTORY = 3073
REGISTER_CLEAR_ALARM_TRIP = 3074
REGISTER_REMOTE_MANUAL_TRIP = 3076
REGISTER_ARC_SELFTEST = 3077
REGISTER_ALARM_FUNCTION_MGMT_2 = 2849  # 0x0B21
REGISTER_TRIP_ACTION_MGMT_2 = 2852  # 0x0B24
REMOTE_TRIP_ENABLE_BIT = 1 << 14

CONF_CONTROLLER_SLAVES = "controller_slaves"
CONF_CONTROLLER_NAMES = "controller_names"
CONF_REQUIRE_ONLINE = "require_online"

DEFAULT_CONTROLLER_SLAVES = "240,241,242"
DEFAULT_CONTROLLER_NAMES = "Kasten V1,Kasten V2,Kasten V3"
DEFAULT_REQUIRE_ONLINE = True

CONF_CHANNEL_COUNT = "channel_count"
CONF_CHANNEL_DESCRIPTIONS = "channel_descriptions"
DEFAULT_CHANNEL_COUNT = 8
MAX_CHANNEL_COUNT = 24
DEFAULT_DI_DESCRIPTIONS = ("DI1", "DI2", "DI3", "DI4")
